src/OnlineCourse.WebCore/Models/ErrorViewModel.cs
using System;

namespace OnlineCourse.WebCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/OnlineCourse.WebCore/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineCourse.Domain.Courses;
using OnlineCourse.Web.Util;

namespace OnlineCourse.Web.Controllers
{
    public class CourseController : Controller
    {
        private readonly CourseService _courseService;

        public CourseController(CourseService courseService)
        {
            _courseService = courseService;
        }
        public ActionResult Index()
        {
            var courses = _courseService.GetAll();
            return View("Index", PaginatedList<CourseDTO>.Create(courses, Request));

        }

        public IActionResult Update(int id)
        {
            var courseDTO = _courseService.GetById(id);
            return View("CreateOrUpdate", courseDTO);
        }

        public IActionResult Create()
        {
            return View("CreateOrUpdate", new CourseDTO());
        }

        public IActionResult Save(CourseDTO model) {
            _courseService.Save(model);
            return RedirectToAction("Index");
        }

    }
}

src/OnlineCourse.WebCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OnlineCourse.WebCore.Models;

namespace OnlineCourse.WebCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/OnlineCourse.WebCore/Views/Course/CreateOrUpdate.cshtml
@model OnlineCourse.Domain.Courses.CourseDTO
@{
    @if (Model.Id > 0)
    {
        ViewData["Title"] = "Update Course";
    }
    else { ViewData["Title"] = "Create Course"; }
}

<div id="pad-wrapper">

    <div class="row">
        <div class="col-md-12">
            <a href="/Curso" class="btn">Voltar</a>
        </div>
    </div>
    <div class="row header">
        <div class="col-md-1">
            <h3>Cursos</h3>
        </div>
    </div>
    <div class="row form-wrapper">
        <div class="col-md-12">
            <form id="form" class="form-horizontal" asp-action="Save" asp-controller="Course" asp-anti-forgery
                  data-ajax="true" data-ajax-method="POST" data-ajax-failure="formQuandoFalha" data-ajax-success="window.location = '/Course/Index'">
                <input type="hidden" class="form-control" asp-for="Id">
                <div class="form-group">
                    <label class="col-md-2 control-label">Nome</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" asp-for="Name">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Descrição</label>
                    <div class="col-md-8">
                        <textarea type="text" class="form-control" asp-for="Description"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Carga Horária</label>
                    <div class="col-md-2">
                        <input type="text" class="form-control" asp-for="Workload">
                        <span asp-validation-for="Workload" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Público Alvo</label>
                    <div class="col-md-2">
                        <select class="form-control" asp-for="TargetAudience">
                            <option value="Estudante">Estudante</option>
                            <option value="Universitário">Universitário</option>
                            <option value="Empregado">Empregado</option>
                            <option value="Empreendedor">Empreendedor</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Valor</label>
                    <div class="col-md-2">
                        <input class="form-control" asp-for="CourseFee">
                        <span asp-validation-for="CourseFee" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                        <button class="btn btn-success">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery.validate.unobtrusive.js"></script>
    <script src="/js/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/js/domainException.js"></script>
}

src/OnlineCourse.WebCore/Views/Course/Index.cshtml
@using OnlineCourse.Web.Util
@using OnlineCourse.Domain.Courses
@model PaginatedList<CourseDTO>
@{
    ViewData["Title"] = "Course List";
}

<div id="pad-wrapper">

    <div class="row">
        <div class="col-md-12">
            <a href="/Cursos" class="btn">Voltar</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <a href="/Course/Create" class="btn btn-primary">Novo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Carga Horária</th>
                        <th>Publico Alvo</th>
                        <th>Valor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Workload
                            </td>
                            <td>
                                @item.TargetAudience
                            </td>
                            <td>
                                @item.CourseFee
                            </td>
                            <td>
                                <a href="/Course/Update/@item.Id" class="btn">Editar</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }

            <a asp-action="Index"
               asp-route-page="@(Model.PageIndex - 1)"
               class="btn btn-default @prevDisabled">
                Anterior
            </a>
            <a asp-action="Index"
               asp-route-page="@(Model.PageIndex + 1)"
               class="btn btn-default @nextDisabled">
                Próximo
            </a>
        </div>
    </div>
</div>

src/OnlineCourse.WebCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/OnlineCourse.WebCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CursoOnline.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/css/toastr.min.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CursoOnline.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Course" asp-action="Index">Curso</a></li>
                    <li><a asp-area="" asp-controller="Aluno" asp-action="Index">Aluno</a></li>
                    <li><a asp-area="" asp-controller="Matricula" asp-action="Index">Matricula</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CursoOnline.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script src="~/js/toastr.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>